### ISSUE TITLE
Getting KeyError: key not found: :type

### ISSUE THREAD

**Issue by Atul9** [danascheider/json_test_data#16]
I installed the gem.
In irb I required it 

>> require 'json_test_data'
=> true

>> data  = JsonTestData.generate!({:a => "b"}.to_json)
KeyError: key not found: :type
	from /home/atul/.rvm/gems/ruby-2.3.0/gems/json_test_data-0.1.0/lib/json_test_data/json_schema.rb:18:in `fetch'
	from /home/atul/.rvm/gems/ruby-2.3.0/gems/json_test_data-0.1.0/lib/json_test_data/json_schema.rb:18:in `generate_data'
	from /home/atul/.rvm/gems/ruby-2.3.0/gems/json_test_data-0.1.0/lib/json_test_data/json_schema.rb:36:in `generate'
	from /home/atul/.rvm/gems/ruby-2.3.0/gems/json_test_data-0.1.0/lib/json_test_data/json_schema.rb:13:in `generate_example'
	from /home/atul/.rvm/gems/ruby-2.3.0/gems/json_test_data-0.1.0/lib/json_test_data.rb:7:in `generate!'
	from (irb):2
	from /home/atul/.rvm/rubies/ruby-2.3.0/bin/irb:11:in '<main>'

**Comment by danascheider** [comment]
So the issue here is that the JSON object you're putting into the `JsonTestData.generate!
